name: CI/CD Pipeline for FinAgent

on:
  push:
    branches:
      - master
      - Features
  pull_request:
    branches:
      - master
      - Features

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest black

      - name: Run tests
        run: |
          pytest tests --verbose --cov=src --cov-report=xml

      - name: Check code formatting
        run: |
          black --check src/

      - name: Notify on failure
        if: failure()
        run: echo "Build failed! Please check logs."

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/finagent:${{ github.sha }},${{ secrets.DOCKER_USERNAME }}/finagent:latest

      - name: Output run instructions
        run: |
          echo "Docker image built and pushed successfully!"
          echo "To run locally, use the following commands:"
          echo "  docker pull ${{ secrets.DOCKER_USERNAME }}/finagent:latest"
          echo "  docker run -p 8501:8501 ${{ secrets.DOCKER_USERNAME }}/finagent:latest"
          echo "Then open http://localhost:8501 in your browser."